apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: movie-bill-serv
  name: movie-bill-serv-deployment
  namespace: movie-qtm
spec:
  replicas: 1
  revisionHistoryLimit: 11
  selector:
    matchLabels:
      app: movie-bill-serv
  template:
    metadata:
      labels:
        app: movie-bill-serv
      namespace: movie-qtm
    spec:
      containers:
        - image: hoangvn2k4/movie-bill-serv:v1
          imagePullPolicy: Always
          name: movie-bill-serv
          ports:
            - containerPort: 8800
              name: tcp
              protocol: TCP
          env:
            - name: MONGO_URL
              value: 'mongodb://movie-bill-db-service:27017/bills'

---
apiVersion: v1
kind: Service
metadata:
  name: movie-bill-serv-service
  namespace: movie-qtm
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp
      port: 8800
      protocol: TCP
      targetPort: 8800
  selector:
    app: movie-bill-serv
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movie-bill-serv-ingress
  namespace: movie-qtm
spec:
  ingressClassName: nginx
  rules:
    - host: api-movie-qtm.qtmdoan.vn
      http:
        paths:
          - backend:
              service:
                name: movie-bill-serv-service
                port:
                  number: 8800
            path: /api/bills/
            pathType: ImplementationSpecific
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: movie-bill-depl-scaler
  namespace: movie-qtm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: deployment
    name: movie-bill-serv-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: "4m"
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: "90Mi"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
        - type: Pods
          value: 1
          periodSeconds: 60
      selectPolicy: Max
