apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movie-user-pvc
  namespace: movie-qtm
spec:
  selector:
    matchLabels:
      app: movie-user-db-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: premium-rwo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movie-bill-pvc
  namespace: movie-qtm
spec:
  selector:
    matchLabels:
      app: movie-bill-db-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: premium-rwo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movie-detail-pvc
  namespace: movie-qtm
spec:
  selector:
    matchLabels:
      app: movie-detail-db-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: premium-rwo
